name: TOOLBOXLAP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        $playitPath = "$env:USERPROFILE\playit.exe"
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile $playitPath
        if (!(Test-Path -Path $playitPath)) { throw "Playit installation failed." }

    - name: Enable Remote Desktop and Firewall Rules
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create Admin User
      env:
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: |
        if (-not $env:USER_PASSWORD -or $env:USER_PASSWORD -eq "") {
          Write-Host "USER_PASSWORD is not set. Using default password."
          $password = ConvertTo-SecureString -AsPlainText "sameh791967" -Force
        } else {
          $password = ConvertTo-SecureString -AsPlainText $env:USER_PASSWORD -Force
        }
        Set-LocalUser -Name "runneradmin" -Password $password
        Write-Host "User 'runneradmin' created or updated successfully."

    - name: Start Playit Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PLAYIT_AUTH_KEY }}
      run: |
        if (-not $env:PLAYIT_AUTH_KEY -or $env:PLAYIT_AUTH_KEY -eq "") {
          throw "PLAYIT_AUTH_KEY is not set. Please set it in Secrets."
        }
        $playitPath = "$env:USERPROFILE\playit.exe"
        Start-Process -FilePath $playitPath -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait

    - name: Keep GitHub Runner Alive
      run: |
        Write-Host "Keeping the session alive for remote access."
        Start-Sleep -Seconds 21600  # 6 ساعات
